version: '3.8'

services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"


  auth-service:
    build:
      context: ./auth-service
    ports:
      - "5005:5005"
    depends_on:
      - mongodb

  profile-service:
    build:
      context: ./profile-service
    ports:
      - "5002:5002"
    depends_on:
      - mongodb

  dashboard-service:
    build:
      context: ./dashboard-service
    ports:
      - "5003:5003"
    depends_on:
      - mongodb

  feedback-service:
    build:
      context: ./feedback-service
    ports:
      - "5004:5004"
    depends_on:
      - mongodb


 

